# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Other
description: Multithreaded evaluation using Arrows
extra-source-files:
- package.yaml
- stack.yaml
ghc-options: -Wall
github: s4ke/Parrows
library:
  dependencies:
  - base
  - deepseq
  - split
  source-dirs: src/main
tests:
  spec:
    source-dirs: src/test
    main: DefinitionSpec.hs
    dependencies:
      - hspec == 2.*
      - base
      - Parrows
      - split
license: MIT
maintainer: Martin Braun
name: Parrows
synopsis: Multithreaded evaluation using Arrows

version: '0.1.0.2'
