# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Parallelism,Arrows
description:
  Arrows are a suitable abstraction for parallel programming.
  This package offers a general interface for parallelizing Arrows.
  This package however only contains the interface and code written against it
  must be used with a backend such as @Parallel-Arrows-Multicore@,
  @Parallel-Arrows-ParMonad@, @Parallel-Arrows-Eden@ in order to have any parallel speedup.
  This package also contains some parallel skeletons such as variants of parMap
  and some topology skeletons.

  For more info, check out the paper at https://arxiv.org/abs/1801.02216
extra-source-files:
- package.yaml
- stack.yaml
ghc-options: -Wall
github: s4ke/Parrows
library:
  dependencies:
  - base >= 4.7 && < 5.0
  - deepseq
  - split
  source-dirs: src/main
license: MIT
license-file: LICENSE.md
maintainer: Martin Braun
name: Parallel-Arrows-Definition
synopsis: Multithreaded evaluation using Arrows.

version: '0.1.1.0'
