name:                Parallel-Arrows-Cloud-Haskell-Eval
version:             0.1.0.0
github:              "githubuser/PArrows-Cloud-Haskell-SimpleLocalNet"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/PArrows-Cloud-Haskell-SimpleLocalNet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - distributed-process >= 0.5.0 && < 0.8
    - distributed-process-simplelocalnet > 0.2 && < 0.3
    - template-haskell >= 2.12 && < 2.13
