flags: {}
extra-package-dbs: []
packages:
- ../Definition
- location:
    git: https://github.com/s4ke/HdpH
    commit: 6263798e3d3a2b83f4d5ad463c45c2698d446245
  subdirs:
  - hdph
  extra-dep: true
- '.'
extra-deps:
- cereal-0.4.1.1
- data-accessor-0.2.2.7
- hashable-1.2.4.0
- mtl-2.2.1
- network-2.6.3.1
- network-info-0.2.0.8
- network-multicast-0.1.2
- network-transport-0.4.4.0
- network-transport-tcp-0.5.1
- packman-0.3.0
- primitive-0.6.1.0
- random-1.1
- split-0.2.3.1
- text-1.2.2.1
- unordered-containers-0.2.7.1
resolver: ghc-7.10.3
