aspell -c -t abstract.tex
aspell -c -t arrows.tex
aspell -c -t basicSkeletons.tex
aspell -c -t benchmarks.tex
aspell -c -t benchmarks_tmp.tex
aspell -c -t conclusion.tex
aspell -c -t futures.tex
aspell -c -t lhs2TeXSafeCommands.tex
aspell -c -t main.tex
aspell -c -t mapSkeletons.tex
aspell -c -t motivation.tex
aspell -c -t output.tex
aspell -c -t parallelHaskells.tex
aspell -c -t parrows.tex
aspell -c -t prelude.tex
aspell -c -t references.tex
aspell -c -t relwork.tex
aspell -c -t syntacticSugar.tex
aspell -c -t topologySkeletons.tex
aspell -c -t utilityFunctions.tex
