name:                Parallel-Arrows-Cloud-Haskell-SimpleLocalNet
version:             0.1.0.0
github:              "githubuser/PArrows-Cloud-Haskell-SimpleLocalNet"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/PArrows-Cloud-Haskell-SimpleLocalNet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring >= 0.9 && < 0.11
    - network >= 2.3 && < 2.7
    - network-multicast >= 0.1.1 && < 0.3
    - data-accessor >= 0.2 && < 0.3
    - binary >= 0.6.3 && < 0.9
    - containers >= 0.4 && < 0.6
    - transformers >= 0.2 && < 0.6
    - network-transport >= 0.5 && < 0.6
    - network-transport-tcp >= 0.4 && < 0.7
    - distributed-process >= 0.5.0 && < 0.8
    - packman >= 0.5 && < 0.6
    - Parallel-Arrows-Definition >= 0.1 && < 0.2
    - Parallel-Arrows-Cloud-Haskell-Eval >= 0.1 && < 0.2
    - array >= 0.5 && < 0.6
    - distributed-process-simplelocalnet > 0.2 && < 0.3
    - deepseq >= 1.4 && < 1.5
    - random >= 1.1 && < 1.2
    - ghc-prim >= 0.5 && < 0.6
