flags: {}
extra-package-dbs: []
packages:
- location:
    git: https://github.com/s4ke/HdpH.git
    commit: b5b269b8ba0e0f35a08d69fd8a01564649fb0caa
  subdirs:
  - hdph
  - hdph-closure
  extra-dep: true
- '.'
extra-deps:
- cereal-0.4.1.1
- data-accessor-0.2.2.7
- hashable-1.2.4.0
- mtl-2.1.3.1
- network-2.6.3.1
- network-info-0.2.0.8
- network-multicast-0.0.12
- network-transport-0.4.4.0
- network-transport-tcp-0.4.2
- primitive-0.6.2.0
- random-1.1
- split-0.2.3.1
- text-1.2.2.1
- unordered-containers-0.2.7.1
resolver: ghc-7.8.4
