# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Parallelism,Arrows
description: BaseSpecs used for @Parallel-Arrows-Definition@ and Co.
  This package contains tests for basic features and even skeletons.
  See the tests for the dummy backend (from @Parallel-Arrows-Definition@) in @src/test@
  or one of the backends (e.g. @Parallel-Arrows-Multicore@) for actual implementations.
extra-source-files:
- package.yaml
- stack.yaml
ghc-options: -Wall
github: s4ke/Parrows
library:
  dependencies:
  - base >= 4.7 && < 5.0
  - hspec == 2.*
  - deepseq
  - split
  - Parallel-Arrows-Definition == 0.1.1.0
  source-dirs: src/main
tests:
  spec:
    source-dirs: src/test
    main: DefinitionSpec.hs
    dependencies:
      - hspec == 2.*
      - base
      - Parallel-Arrows-BaseSpec
      - Parallel-Arrows-Definition == 0.1.1.0
      - split
license: MIT
license-file: LICENSE.md
maintainer: Martin Braun
name: Parallel-Arrows-BaseSpec
synopsis: BaseSpecs used for @Parallel-Arrows-Definition@ and Co.

version: '0.1.1.0'
