# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Parallelism,Arrows
synopsis: Par Monad (@monad-par@) based backend for @Parallel-Arrows-Definition@.
extra-source-files:
- package.yaml
- stack.yaml
ghc-options: -Wall
github: s4ke/Parrows
library:
  dependencies:
  - base >= 4.7 && < 5.0
  - deepseq
  - monad-par
  - split
  - Parallel-Arrows-Definition == 0.1.1.0
  source-dirs: src/main
tests:
  spec:
    source-dirs:
      - src/test
    main: Spec.hs
    dependencies:
      - hspec == 2.*
      - base
      - deepseq
      - monad-par
      - split
      - Parallel-Arrows-Definition == 0.1.1.0
      - Parallel-Arrows-BaseSpec == 0.1.1.0
      - Parallel-Arrows-ParMonad == 0.1.1.0
license: MIT
license-file: LICENSE.md
maintainer: Martin Braun
name: Parallel-Arrows-ParMonad
synopsis: Par Monad (@monad-par@) based backend for @Parallel-Arrows-Definition@.
version: '0.1.1.0'
